---
- name: Check for existing installation
  service_facts:

- name: Install Argon EON services
  shell: curl https://download.argon40.com/argoneon.sh | bash
  when: >
    'argoneond.service' not in services or
    'argononed.service' not in services

- name: "{{ argoneon_enable_rtc_service | ternary('Enable', 'Disable') }} RTC service"
  service:
    name: argoneond
    state: "{{ argoneon_enable_rtc_service | ternary('started', 'stopped') }}"
    enabled: "{{ argoneon_enable_rtc_service }}"

- name: "{{ argoneon_enable_fan_lcd_service | ternary('Enable', 'Disable') }} LCD and fan service"
  service:
    name: argononed
    state: "{{ argoneon_enable_fan_lcd_service | ternary('started', 'stopped') }}"
    enabled: "{{ argoneon_enable_fan_lcd_service }}"
